# Uygulama adi
spring.application.name=ReservationSystem
# Loglama ayarlari:
logging.file.name=reservation-system.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Sunucu ayarlari
server.port=8080
server.ssl.enabled=false
# E-posta sunucu ayarlari
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ihsanenes5325@gmail.com
spring.mail.password=voxy cryn tlag njcg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

